
desktop:
  framework: vision
  background:
    style: mesh
    colors:
      - "hsla(280, 80%, 70%, 1)"
      - "hsla(200, 90%, 65%, 1)"
      - "hsla(330, 80%, 75%, 1)"
      - "hsla(40, 90%, 70%, 1)"
    src: "https://slepingbearhotels.com/wp-content/uploads/2025/05/Where-Is-Durdle-Door.webp"
    color: "#d6d3ff"
  foreground:
    color: "#000000"

layout:
  columns: 12
  components:
    - name: Clock
      type: widget
      component: UIAnalogClockWidget
      props:
        timezone: "Europe/London"

    - name: "AirplanesLive"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Airplanes.live"
        url: "https://airplanes.live/myfeed/"
        icon: "flightradar24"

    - name: "tar1090"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Tar1090"
        url: "http://192.168.1.201/tar1090/"
        icon: "flightradar24"

    - name: "adsbexchange"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "ADSB-Exchange"
        url: "https://globe.adsbexchange.com"
        icon: "flightradar24"

    - name: "GLiNet"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "GLiNet"
        url: "https://192.168.1.1/#/login"
        icon: "openwrt"

    - name: "Github"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Github"
        url: "https://www.github.com"
        icon: "github"

    - name: "Docker"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Docker Hub"
        url: "https://hub.docker.com"
        icon: "docker"

    - name: "Webtop"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Webtop"
        url: "https://webtop.lan:8086"
        icon: "webtop"

    - name: "Pi-Hole"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Pi-Hole"
        url: "http://192.168.1.202:3080/admin"
        icon: "pi-hole"

    - name: "wud"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Wud"
        url: "http://192.168.1.202:3000"
        icon: "wud"

    - name: "Jellyfin"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Jellyfin"
        url: "http://jellyfin.pi5.lan/"
        icon: "jellyfin"

    - name: "arr"
      type: folder
      props:
        label: "Arrr"
        icon: "file-explorer"
      components:
        - name: "Prowlarr"
          type: app-icon
          component: UIAppIconButton
          props:
            label: "Prowlarr"
            url: "http://prowlarr.pi5.lan"
            icon: "prowlarr"

        - name: "Jellyseerr"
          type: app-icon
          component: UIAppIconButton
          props:
            label: "Jellyseerr"
            url: "http://jellyseerr.pi5.lan"
            icon: "jellyseerr"

        - name: "Radarr"
          type: app-icon
          component: UIAppIconButton
          props:
            label: "Radarr"
            url: "http://radarr.pi5.lan"
            icon: "radarr"

        - name: "Lidarr"
          type: app-icon
          component: UIAppIconButton
          props:
            label: "Lidarr"
            url: "http://lidarr.pi5.lan"
            icon: "lidarr"

        - name: "Sonarr"
          type: app-icon
          component: UIAppIconButton
          props:
            label: "Sonarr"
            url: "http://sonarr.pi5.lan"
            icon: "sonarr"

        - name: "Transmission"
          type: app-icon
          component: UIAppIconButton
          props:
            label: "Transmission"
            url: "http://transmission.pi5.lan"
            icon: "transmission"

    - name: "vopidy"
      type: app-icon
      component: UIAppIconButton
      props:
        label: "Music"
        url: "https://viox.lan"
        icon: "spotify"

    - name: Weather
      type: custom
      component: UIWeatherWidget
      props:
        location: "current"

    - name: News
      type: custom
      component: UINewsHeadlinesWidget
      props:
        rss: "https://www.oxfordmail.co.uk/news/rss/"
        size: "medium"

    - name: Moon Phase
      type: custom
      component: UISunMoonPhaseWidget
      props:
        location: "current"

    - name: SystemInfo
      type: custom
      component: UISystemInfoWidget
      props:
        location: "current"

    - name: Map
      type: custom
      component: UIMapWidget
      props:
        location: "current"
        apiUser: "rttapi_guidcruncher"
        apiPass: "18162313ab1df4362155bd629633f33139bddb58"

    - name: Calendar
      type: custom
      component: UICalendarWidget
      props:
        location: "current"

    - name: GeoClock
      type: custom
      component: UIGeoclockWidget
      props:
        location: "current"

    - name: UIGBRail
      type: custom
      component: UIGBRailStationWidget
      props:
        stationCode: "DID"
        locationName: "Didcot Parkway"
        apiUser: "rttapi_guidcruncher"
        apiPass: "18162313ab1df4362155bd629633f33139bddb58"

    - name: Clock
      type: widget
      component: UIFlipClockWidget
      props:
        timezone: "Europe/London"
