// Auto-generated by GlassUiRegistry
import Container from './Container.vue'
import FlipCard from './FlipCard.vue'
import LocationDetailCard from './LocationDetailCard.vue'
import MoonPhase from './MoonPhase.vue'
import ResponsiveGrid from './ResponsiveGrid.vue'
import ResponsiveGridItem from './ResponsiveGridItem.vue'
import UIAnalogClockWidget from './UIAnalogClockWidget.vue'
import UIAppIconButton from './UIAppIconButton.vue'
import UIButton from './UIButton.vue'
import UICalendarWidget from './UICalendarWidget.vue'
import UICheckbox from './UICheckbox.vue'
import UIDesktopRenderer from './UIDesktopRenderer.vue'
import UIDropdownList from './UIDropdownList.vue'
import UIDropdownMenu from './UIDropdownMenu.vue'
import UIFlipClockWidget from './UIFlipClockWidget.vue'
import UIFolderView from './UIFolderView.vue'
import UIFolderViewWidget from './UIFolderViewWidget.vue'
import UIGBRailStationWidget from './UIGBRailStationWidget.vue'
import UIGeoclockWidget from './UIGeoclockWidget.vue'
import UIImageBrowser from './UIImageBrowser.vue'
import UIMapWidget from './UIMapWidget.vue'
import UIModalDialog from './UIModalDialog.vue'
import UINewsHeadlinesWidget from './UINewsHeadlinesWidget.vue'
import UIProgressbar from './UIProgressbar.vue'
import UISlider from './UISlider.vue'
import UISparkline from './UISparkline.vue'
import UISunMoonPhaseWidget from './UISunMoonPhaseWidget.vue'
import UISurface from './UISurface.vue'
import UISwitch from './UISwitch.vue'
import UISystemInfoWidget from './UISystemInfoWidget.vue'
import UITabContainer from './UITabContainer.vue'
import UITabPanel from './UITabPanel.vue'
import UITextBox from './UITextBox.vue'
import UIThemeChooser from './UIThemeChooser.vue'
import UIToast from './UIToast.vue'
import UIWeatherWidget from './UIWeatherWidget.vue'
import UIWidgetView from './UIWidgetView.vue'
import YamlEditor from './YamlEditor.vue'
import '../styles/styles.scss'
import { createPinia } from 'pinia'
import { VisualEffect } from '../directives/visualEffect'
import { Background } from '../directives/background'
import { ClickOutside } from '../directives/clickOutside'
import { useThemeStore } from '../stores/themeStore'

export const GlassComponents = {
  Container,
  FlipCard,
  LocationDetailCard,
  MoonPhase,
  ResponsiveGrid,
  ResponsiveGridItem,
  UIAnalogClockWidget,
  UIAppIconButton,
  UIButton,
  UICalendarWidget,
  UICheckbox,
  UIDesktopRenderer,
  UIDropdownList,
  UIDropdownMenu,
  UIFlipClockWidget,
  UIFolderView,
  UIFolderViewWidget,
  UIGBRailStationWidget,
  UIGeoclockWidget,
  UIImageBrowser,
  UIMapWidget,
  UIModalDialog,
  UINewsHeadlinesWidget,
  UIProgressbar,
  UISlider,
  UISparkline,
  UISunMoonPhaseWidget,
  UISurface,
  UISwitch,
  UISystemInfoWidget,
  UITabContainer,
  UITabPanel,
  UITextBox,
  UIThemeChooser,
  UIToast,
  UIWeatherWidget,
  UIWidgetView,
  YamlEditor,
};


export function  UseGlassUi(app) {
    const pinia = createPinia()
    app.directive('click-outside', ClickOutside);
    app.directive('visual-effect', VisualEffect);
    app.directive('background', Background);

    app.use(pinia);
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
    const themeStore = useThemeStore()
    themeStore.restoreTheme()
};
