// Auto-generated by GlassUiRegistry
import Container from './Container.vue'
import FlipCard from './FlipCard.vue'
import IPInfo from './IPInfo.vue'
import IconView from './IconView.vue'
import MKMapView from './MKMapView.vue'
import ResponsiveGrid from './ResponsiveGrid.vue'
import ResponsiveGridItem from './ResponsiveGridItem.vue'
import UIActivityIndicator from './UIActivityIndicator.vue'
import UIAlert from './UIAlert.vue'
import UIAnalogClock from './UIAnalogClock.vue'
import UIAppIconItem from './UIAppIconItem.vue'
import UIAppIconLink from './UIAppIconLink.vue'
import UIButton from './UIButton.vue'
import UICalendarWidget from './UICalendarWidget.vue'
import UICollectionView from './UICollectionView.vue'
import UICollectionViewItem from './UICollectionViewItem.vue'
import UIColorPicker from './UIColorPicker.vue'
import UIContentPanel from './UIContentPanel.vue'
import UIDatePicker from './UIDatePicker.vue'
import UIDesktopRenderer from './UIDesktopRenderer.vue'
import UIDropdownList from './UIDropdownList.vue'
import UIDropdownMenu from './UIDropdownMenu.vue'
import UIDropdownMenuItem from './UIDropdownMenuItem.vue'
import UIDropdownMenuTrigger from './UIDropdownMenuTrigger.vue'
import UIFlipClock from './UIFlipClock.vue'
import UIFolderView from './UIFolderView.vue'
import UIFolderViewWidget from './UIFolderViewWidget.vue'
import UIImage from './UIImage.vue'
import UIImageView from './UIImageView.vue'
import UIListPicker from './UIListPicker.vue'
import UIMapWidget from './UIMapWidget.vue'
import UIMenubar from './UIMenubar.vue'
import UIModalDialog from './UIModalDialog.vue'
import UINavigationBar from './UINavigationBar.vue'
import UINewsHeadlinesWidget from './UINewsHeadlinesWidget.vue'
import UINotificationBar from './UINotificationBar.vue'
import UIPageControl from './UIPageControl.vue'
import UIPopover from './UIPopover.vue'
import UIProgressView from './UIProgressView.vue'
import UISearchBar from './UISearchBar.vue'
import UISegmentedControl from './UISegmentedControl.vue'
import UISlider from './UISlider.vue'
import UISplitView from './UISplitView.vue'
import UIStepper from './UIStepper.vue'
import UISunMoonPhaseWidget from './UISunMoonPhaseWidget.vue'
import UISwitch from './UISwitch.vue'
import UITabBar from './UITabBar.vue'
import UITabItem from './UITabItem.vue'
import UITableCell from './UITableCell.vue'
import UITableView from './UITableView.vue'
import UITextField from './UITextField.vue'
import UITextView from './UITextView.vue'
import UIThemeChooser from './UIThemeChooser.vue'
import UITimePicker from './UITimePicker.vue'
import UITodolistWidget from './UITodolistWidget.vue'
import UIToolbar from './UIToolbar.vue'
import UIView from './UIView.vue'
import UIVisualEffectView from './UIVisualEffectView.vue'
import UIWeatherWidget from './UIWeatherWidget.vue'
import UIWheelListView from './UIWheelListView.vue'
import UIWidgetView from './UIWidgetView.vue'
import '../styles/styles.scss'
import { createPinia } from 'pinia'
import { VisualEffect } from '../directives/visualEffect'
import { Background } from '../directives/background'
import { ClickOutside } from '../directives/clickOutside'
import { useThemeStore } from '../stores/themeStore'

export const GlassComponents = {
  Container,
  FlipCard,
  IPInfo,
  IconView,
  MKMapView,
  ResponsiveGrid,
  ResponsiveGridItem,
  UIActivityIndicator,
  UIAlert,
  UIAnalogClock,
  UIAppIconItem,
  UIAppIconLink,
  UIButton,
  UICalendarWidget,
  UICollectionView,
  UICollectionViewItem,
  UIColorPicker,
  UIContentPanel,
  UIDatePicker,
  UIDesktopRenderer,
  UIDropdownList,
  UIDropdownMenu,
  UIDropdownMenuItem,
  UIDropdownMenuTrigger,
  UIFlipClock,
  UIFolderView,
  UIFolderViewWidget,
  UIImage,
  UIImageView,
  UIListPicker,
  UIMapWidget,
  UIMenubar,
  UIModalDialog,
  UINavigationBar,
  UINewsHeadlinesWidget,
  UINotificationBar,
  UIPageControl,
  UIPopover,
  UIProgressView,
  UISearchBar,
  UISegmentedControl,
  UISlider,
  UISplitView,
  UIStepper,
  UISunMoonPhaseWidget,
  UISwitch,
  UITabBar,
  UITabItem,
  UITableCell,
  UITableView,
  UITextField,
  UITextView,
  UIThemeChooser,
  UITimePicker,
  UITodolistWidget,
  UIToolbar,
  UIView,
  UIVisualEffectView,
  UIWeatherWidget,
  UIWheelListView,
  UIWidgetView,
}

export function UseGlassUi(app) {
  const pinia = createPinia()
  app.directive('click-outside', ClickOutside)
  app.directive('visual-effect', VisualEffect)
  app.directive('background', Background)

  app.use(pinia)
  Object.keys(GlassComponents).forEach((name) => {
    app.component(name, GlassComponents[name])
  })
  const themeStore = useThemeStore()
  themeStore.restoreTheme()
}
